//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcReduxLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public string Channel_ID { get; set; }
        public string Branch_Type { get; set; }
        public string Branch_ID { get; set; }
        public string Branch_Name { get; set; }
        public string Supervisor { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Address_City { get; set; }
        public string Address_Dist { get; set; }
        public string Address_ZIP_code { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Type_Desc { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Payment_Type_Bank_Account_Bank { get; set; }
        public string Payment_Type_Bank_Account_Post { get; set; }
        public string Payment_Type_Bank_Account_ATM { get; set; }
        public string MessagePay_Limit { get; set; }
        public string Business_Area { get; set; }
    }
}
