//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcReduxLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL
    {
        public string Channel_ID { get; set; }
        public string Channel_Type { get; set; }
        public string BAN_NO { get; set; }
        public string Company_Name { get; set; }
        public string Company_Phone { get; set; }
        public string Address_city { get; set; }
        public string Address_dist { get; set; }
        public string Address_Post_Code { get; set; }
        public string Address_Address { get; set; }
        public string Meridian_policy_NO { get; set; }
        public string Producer_Code { get; set; }
        public System.DateTime Producer_Date { get; set; }
        public string Contact_Note { get; set; }
        public string Contact_Note_Email { get; set; }
        public string Contact_Commission { get; set; }
        public string Contact_Commission_Email { get; set; }
        public string Commission_Date { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Type_Desc { get; set; }
        public System.DateTime Contract_Date { get; set; }
        public string Contact1 { get; set; }
        public string Contact1_Phone { get; set; }
        public string Contact1_Email { get; set; }
        public string Contact2 { get; set; }
        public string Contact2_Phone { get; set; }
        public string Contact2_Email { get; set; }
        public string Contact3 { get; set; }
        public string Contact3_Phone { get; set; }
        public string Contact3_Email { get; set; }
        public string Status { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Effect_Type { get; set; }
        public string Pac_Line { get; set; }
        public string Product_Code { get; set; }
        public string Business_SuperVisior { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Contact_Commission_Phone { get; set; }
        public string Contact_Commission_Fax { get; set; }
        public string Contact_Commission_City { get; set; }
        public string Contact_Commission_Dict { get; set; }
        public string Contact_Commission_PostCode { get; set; }
        public string Contact_Commission_Address { get; set; }
        public string Contact_Note_Phone { get; set; }
        public string Contact_Note_Fax { get; set; }
        public string Contact_Note_City { get; set; }
        public string Contact_Note_Dict { get; set; }
        public string Contact_Note_PostCode { get; set; }
        public string Contact_Note_Address { get; set; }
        public string Contact1_Fax { get; set; }
        public string Contact1_City { get; set; }
        public string Contact1_Dict { get; set; }
        public string Contact1_PostCode { get; set; }
        public string Contact1_Address { get; set; }
        public string Contact2_Fax { get; set; }
        public string Contact2_City { get; set; }
        public string Contact2_Dict { get; set; }
        public string Contact2_PostCode { get; set; }
        public string Contact2_Address { get; set; }
        public string Contact3_Fax { get; set; }
        public string Contact3_City { get; set; }
        public string Contact3_Dict { get; set; }
        public string Contact3_PostCode { get; set; }
        public string Contact3_Address { get; set; }
        public string OnLine_Status { get; set; }
        public string OffLine_Status { get; set; }
        public string Contract_Status { get; set; }
        public string ChangePassword_Limit { get; set; }
        public Nullable<int> Settlement_Date { get; set; }
        public string Time_Limit { get; set; }
        public string MessagePay_Limit { get; set; }
        public string Search_Limit { get; set; }
        public string Group { get; set; }
        public string Business_Area { get; set; }
        public Nullable<int> Limit_Hour { get; set; }
        public string Payment_Type_Bank_Account_Bank { get; set; }
        public string Payment_Type_Bank_Account_Post { get; set; }
        public string Payment_Type_Bank_Account_ATM { get; set; }
        public string Notification_Letter { get; set; }
        public string BigPolicy_Active { get; set; }
        public string Meridian_policy_NO_B { get; set; }
    }
}
