//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcReduxLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductV2
    {
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Ins1 { get; set; }
        public string Ins2 { get; set; }
        public string Ins3 { get; set; }
        public string TI1 { get; set; }
        public string TI2 { get; set; }
        public string TI3 { get; set; }
        public string Remark { get; set; }
        public string Ins1TI1 { get; set; }
        public string Ins1TI2 { get; set; }
        public string Ins1TI3 { get; set; }
        public string Ins2TI1 { get; set; }
        public string Ins2TI2 { get; set; }
        public string Ins2TI3 { get; set; }
        public string Ins3TI1 { get; set; }
        public string Ins3TI2 { get; set; }
        public string Ins3TI3 { get; set; }
    }
}
