//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcReduxLab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReactPracticeEntities : DbContext
    {
        public ReactPracticeEntities()
            : base("name=ReactPracticeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<CHANNEL> CHANNEL { get; set; }
        public virtual DbSet<Channel_VS_Product> Channel_VS_Product { get; set; }
        public virtual DbSet<ExpLog> ExpLog { get; set; }
        public virtual DbSet<ZIP_CODE> ZIP_CODE { get; set; }
        public virtual DbSet<ProductV2> ProductV2 { get; set; }
        public virtual DbSet<Remittance_Account> Remittance_Account { get; set; }
    }
}
